version: '0.1'
services:
  database:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: hagrid
      MYSQL_DATABASE: kirjakanta
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database/skriptit/luontiskripti.sql:/docker-entrypoint-initdb.d/luontiskripti.sql

volumes:
  db_data: