services:
  app:
    image: heikamal/kirjaarkistoapp
    entrypoint: ["nginx", "-g", "daemon off;"]
    ports:
      - '80:80'
  database:
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: kirjakanta
      MYSQL_USER: dbuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
  server:
    image: heikamal/kirjaarkistoserver
    entrypoint: "/bin/sh -c 'MYSQL_HOST=database MYSQL_USER=dbuser MYSQL_PASSWORD=`cat /run/secrets/db_user_password` MYSQL_DATABASE=kirjakanta ENVIRONMENT_TAG=dev SENDREPORT_URI=rofl@copter.lol API_VERSION=1.0 JWT_SECRET=`cat /run/secrets/jwt_secret` JWT_EXPIRATION_MS=3600000 API_ADMIN_PASSWORD=`cat /run/secrets/api_admin_password` java -Djava.security.egd=file:/dev/./urandom -jar /kirjaarkisto.jar'"
    environment:
      MYSQL_HOST: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: /run/secrets/db_user_password
      MYSQL_DATABASE: kirjakanta
      ENVIRONMENT_TAG: prod
      SENDREPORT_URI: rofl@copter.lol
      API_VERSION: 0.4
      JWT_SECRET: /run/secrets/jwt_secret
      JWT_EXPIRATION_MS: 3600000
      API_ADMIN_PASSWORD: /run/secrets/api_admin_password
    ports:
      - '8080:8080'
    links:
      - database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: 
      - ./server:/app
    secrets:
      - db_user_password
      - api_admin_password
      - jwt_secret

secrets:
  db_root_password:
    external: true
  db_user_password:
    external: true
  api_admin_password:
    external: true
  jwt_secret:
    external: true

volumes:
  db_data:
